#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html #/var/www/html/index.nginx-debian.html
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/BvWnEiOoAEk permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default
sudo service nginx restart
