#!/usr/bin/env bash
# this script checks if a file exists

FILE=school

if [ -e "$FILE" ]
then
	echo "school file exists"
	if [ ! -s "$FILE" ]
	then
		echo "school is empty"
	else
		echo "school is not empty"
	fi
	if [ -f "$FILE" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
